# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3dd1cbb2bc48925c845ea2cc4ab862c8953cb98a6a608db105bef117a7f84b840c026d165e4a81a26029b2f95f74d4605d3681785f527af7a932ef2a4e3519bd

test:
  secret_key_base: 155a6fea555d6767c6f4fe40dc74048ef2a34b3e3204f989f5fea0a6828292442930ee7756b0360edcab3e42aa3852417a64849ba745c86b17f2e62d0a80879d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
